name: PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: rossjrw/pr-preview-action@v1
        with:
          preview-branch: main
          source-dir: ./src/
          umbrella-dir: previews
